---
#- name: Configure nginx
#  copy:
#    dest: '/etc/radvd.conf'
#    src: radvd.conf
#    owner: root
#    group: root
#    mode: 0644
#  notify:
#  - restart radvd

- name: Create service drop-in directory
  file:
    dest: '/etc/systemd/system/nginx.service.d'
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Start nginx after networks are configured
  copy:
    dest: '/etc/systemd/system/nginx.service.d/wait-online.conf'
    src: wait-online.conf
    owner: root
    group: root
    mode: 0644

- name: Enable nginx service
  systemd:
    name: nginx.service
    enabled: yes
    masked: no
    state: started
  when: not chroot
- name: '- when in chroot'
  command: systemctl enable nginx.service
  when: chroot

# vim: set ts=2 sw=2 et:
